import React from 'react';
import { Headphones, ExternalLink, Play, Pause, Sparkles } from 'lucide-react';
import { cn } from '@/lib/utils';

interface NotebookLMPlayerProps {
  audioUrl: string;
  notebookUrl?: string;
  lang: 'en' | 'ru';
  title?: string;
}

export const NotebookLMPlayer: React.FC<NotebookLMPlayerProps> = ({ audioUrl, notebookUrl, lang, title }) => {
  const [isPlaying, setIsPlaying] = React.useState(false);
  const audioRef = React.useRef<HTMLAudioElement>(null);

  const togglePlay = () => {
    if (audioRef.current) {
      if (isPlaying) {
        audioRef.current.pause();
      } else {
        audioRef.current.play();
      }
      setIsPlaying(!isPlaying);
    }
  };

  return (
    <div className="my-8 overflow-hidden rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-gradient-to-br from-indigo-50/50 to-blue-50/50 dark:from-indigo-950/20 dark:to-blue-950/20 backdrop-blur-sm">
      <div className="px-6 py-5">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div className="flex items-center gap-4">
            <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-indigo-500 text-white shadow-lg shadow-indigo-500/20">
              <Headphones className="h-6 w-6" />
            </div>
            <div className="space-y-1">
              <div className="flex items-center gap-2">
                <span className="text-[10px] font-bold uppercase tracking-widest text-indigo-600 dark:text-indigo-400">
                  NotebookLM AI Overview
                </span>
                <Sparkles className="h-3 w-3 text-amber-500" />
              </div>
              <h4 className="text-sm font-semibold text-zinc-900 dark:text-zinc-100">
                {lang === 'en' ? 'Listen to AI Podcast' : 'Слушать ИИ-подкаст'}
              </h4>
              <p className="text-xs text-zinc-500 dark:text-zinc-400 max-w-md">
                {lang === 'en' 
                  ? 'A deep-dive conversation generated by Google NotebookLM based on this research.' 
                  : 'Глубокое погружение в тему в формате подкаста, созданное Google NotebookLM.'}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={togglePlay}
              className="inline-flex items-center gap-2 rounded-full bg-zinc-900 dark:bg-zinc-100 px-5 py-2.5 text-xs font-semibold text-zinc-100 dark:text-zinc-900 hover:bg-zinc-800 dark:hover:bg-zinc-200 transition-all shadow-md active:scale-95"
            >
              {isPlaying ? (
                <>
                  <Pause className="h-4 w-4 fill-current" />
                  <span>{lang === 'en' ? 'Pause' : 'Пауза'}</span>
                </>
              ) : (
                <>
                  <Play className="h-4 w-4 fill-current" />
                  <span>{lang === 'en' ? 'Play Overview' : 'Слушать обзор'}</span>
                </>
              )}
            </button>

            {notebookUrl && (
              <a
                href={notebookUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex h-10 w-10 items-center justify-center rounded-full border border-zinc-200 dark:border-zinc-700 bg-white dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 hover:text-zinc-900 dark:hover:text-zinc-100 transition-colors"
                title={lang === 'en' ? 'Open in NotebookLM' : 'Открыть в NotebookLM'}
              >
                <ExternalLink className="h-4 w-4" />
              </a>
            )}
          </div>
        </div>

        <audio
          ref={audioRef}
          src={audioUrl}
          onPlay={() => setIsPlaying(true)}
          onPause={() => setIsPlaying(false)}
          onEnded={() => setIsPlaying(false)}
          className="hidden"
        />
        
        {/* Simple Progress Bar (Decorative/Placeholder) */}
        <div className="mt-6 h-1 w-full overflow-hidden rounded-full bg-zinc-200 dark:bg-zinc-800">
          <div 
            className={cn(
              "h-full bg-indigo-500 transition-all duration-300",
              isPlaying ? "w-1/3 animate-pulse" : "w-0"
            )} 
          />
        </div>
      </div>
    </div>
  );
};
